.vscode/
.github/
.git/
*.log
*.tmp
*.temp

**/node_modules/
**/.pnpm-store/
**/dist/
**/coverage/
**/build/

design/
docker/
docs/
fastlane/
machine-learning/
misc/
mobile/
server/
plugins/
i18n/
